# Generated by Django 3.2.4 on 2021-10-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='contenido',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
